
import type { DeedData, NewCreature } from '@/lib/types';

export const defaultDeeds: (DeedData & { deedName: string })[] = [
  {
    deedName: "Coward's Cut",
    name: "Coward's Cut",
    tier: 'light',
    actionType: 'attack',
    deedType: 'melee',
    versus: 'guard',
    target: '1 Creature',
    effects: {
      hit: 'Deal 3 damage (1d6). Move 3.',
      shadow: 'Deal 3 damage (1d6). Move 3.',
    },
    tags: ['melee'],
  },
  {
    deedName: "Crude Bow",
    name: 'Crude Bow',
    tier: 'light',
    actionType: 'attack',
    deedType: 'missile',
    versus: 'guard',
    target: '1 Creature',
    effects: {
      hit: 'Deal 3 damage (1d6).',
      shadow: 'Deal 3 damage (1d6).',
    },
    tags: ['missile'],
  },
  {
    deedName: "Cut & Run",
    name: 'Cut & Run',
    tier: 'light',
    actionType: 'attack',
    deedType: 'melee',
    versus: 'guard',
    target: '1 Creature',
    effects: {
      hit: 'Deal 7 damage (2d6). Move 2.',
      shadow: 'Confer bleeding 2.',
    },
    tags: ['melee'],
  },
  {
    deedName: "Sharp Rock",
    name: 'Sharp Rock',
    tier: 'light',
    actionType: 'attack',
    deedType: 'missile',
    versus: 'guard',
    target: '1 Creature',
    effects: {
      hit: 'Deal 3 damage (1d6).',
      shadow: 'Confer bleeding 2.',
    },
    tags: ['missile'],
  },
  {
    deedName: "Blood-Spiller",
    name: 'Blood-Spiller',
    tier: 'heavy',
    actionType: 'attack',
    deedType: 'melee',
    versus: 'guard',
    target: '1 Creature',
    effects: {
      base: 'Deal 7 damage (2d6).',
      hit: 'Shove 2. The target suffers double damage from bleeding on this forced movement.',
      shadow: 'The target also becomes toppled.',
    },
    tags: ['melee'],
  },
  {
    deedName: "Barbed Arrow",
    name: 'Barbed Arrow',
    tier: 'light',
    actionType: 'attack',
    deedType: 'missile',
    versus: 'guard',
    target: '1 Creature',
    effects: {
      hit: 'Deal 7 damage (2d6).',
      shadow: 'Confer bleeding 2.',
    },
    tags: ['missile'],
  },
  {
    deedName: "Poison Arrow",
    name: 'Poison Arrow',
    tier: 'heavy',
    actionType: 'attack',
    deedType: 'missile',
    versus: 'guard',
    target: '1 Creature',
    effects: {
      base: 'Deal 3 damage (1d6).',
      hit: 'Confer poisoned 2.',
      shadow: 'Confer poisoned 4 instead.',
    },
    tags: ['missile', 'poison'],
  },
  {
    deedName: 'Jagged Axe',
    name: 'Jagged Axe',
    tier: 'light',
    actionType: 'attack',
    deedType: 'melee',
    versus: 'guard',
    target: '1 creature',
    effects: {
      hit: 'Deal 9 damage (2d8).',
      shadow: 'Confer frail 2.',
    },
    tags: ['melee'],
  },
  {
    deedName: 'Smashing Strike',
    name: 'Smashing Strike',
    tier: 'heavy',
    actionType: 'attack',
    deedType: 'melee',
    versus: 'guard',
    target: '1 creature',
    effects: {
      base: 'Deal 9 damage (2d8). Push 2.',
      hit: 'Add 4 damage (1d8). Confer toppled 2.',
    },
    tags: ['melee', 'forced movement', 'control'],
  },
  {
    deedName: 'Bolstering Cleave',
    name: 'Bolstering Cleave',
    tier: 'mighty',
    actionType: 'attack',
    deedType: 'melee',
    versus: 'guard',
    target: 'close spread 1',
    effects: {
      base: 'Deal 4 damage (1d8).',
      hit: 'Deal 9 damage (2d8).\nAfter: This creature makes a recovery x, where x is the number of targets that were hit.',
    },
    tags: ['melee', 'cleave', 'healing'],
  },
  {
    deedName: 'War Blade',
    name: 'War Blade',
    tier: 'light',
    actionType: 'attack',
    deedType: 'melee',
    versus: 'guard',
    target: '1 creature',
    effects: {
      hit: 'Deal 7 damage (2d6). Push 2.',
      shadow: 'Confer unguarded 2.',
    },
    tags: ['melee', 'forced movement'],
  },
  {
    deedName: "Warbringer's Blessing",
    name: "Warbringer's Blessing",
    tier: 'light',
    actionType: 'support',
    deedType: 'innate',
    versus: '10',
    target: '1 creature',
    effects: {
      hit: 'Confer strong 2. The target gains one extra action point at the start of its next turn. It can make an additional light attack deed this turn.',
    },
    tags: ['buff'],
  },
  {
    deedName: "Warbringer's Threat",
    name: "Warbringer's Threat",
    tier: 'heavy',
    actionType: 'support',
    deedType: 'innate',
    versus: '10',
    target: '1 creature',
    effects: {
      hit: 'Choose one defeated goblin in range. It regains half its missing hit points and stands up from toppled.\nIt takes a turn after the chieftain this round.',
    },
    tags: ['healing', 'revive'],
  },
  {
    deedName: 'Mark for Death',
    name: 'Mark for Death',
    tier: 'mighty',
    actionType: 'attack',
    deedType: 'innate',
    versus: 'resist',
    target: '1 creature',
    effects: {
      base: 'Confer unguarded 2. The target takes 1d6 extra damage from goblin attacks this round.',
      hit: 'Confer unguarded 4 instead.',
    },
    tags: ['debuff'],
  },
  {
    deedName: 'Staff',
    name: 'Staff',
    tier: 'light',
    actionType: 'attack',
    deedType: 'melee',
    versus: 'guard',
    target: '1 creature',
    effects: {
      hit: 'Deal 7 damage (2d6).',
      shadow: 'Sweep 1. Confer toppled.',
    },
    tags: ['melee', 'forced movement', 'control'],
  },
  {
    deedName: 'Shadow Bolt',
    name: 'Shadow Bolt',
    tier: 'heavy',
    actionType: 'attack',
    deedType: 'missile',
    versus: 'guard',
    target: '1 creature',
    effects: {
      hit: 'Deal 7 damage (2d6).',
      shadow: 'Confer weary 4.',
    },
    tags: ['missile', 'debuff'],
  },
  {
    deedName: 'Mud Burst',
    name: 'Mud Burst',
    tier: 'mighty',
    actionType: 'attack',
    deedType: 'spell',
    versus: 'resist',
    target: 'blast 3',
    effects: {
      base: 'Deal 3 damage (1d6). Create a field of difficult terrain in the area of effect.',
      hit: 'Add 7 damage (2d6).',
    },
    tags: ['spell', 'area of effect', 'control'],
  },
  {
    deedName: 'Blood Bomb',
    name: 'Blood Bomb',
    tier: 'mighty',
    actionType: 'attack',
    deedType: 'spell',
    versus: 'resist',
    target: 'spread 2',
    effects: {
      start: 'Choose one ally in range 8. The attack targets all creatures in a spread 2 centered on that creature.',
      base: 'Deal 7 damage (2d6). The chosen ally is killed.',
      hit: 'Add 3 damage (1d6). Confer poisoned 4.',
    },
    tags: ['spell', 'area of effect', 'poison', 'sacrificial'],
  },
];

export const defaultCreatures: (Omit<NewCreature, 'deeds'> & { deedNames: string[] })[] = [
  {
    name: 'Goblin Drudge',
    level: 1,
    role: 'Harrier',
    template: 'Underling',
    TR: 3,
    attributes: {
      HP: 1,
      Speed: 6,
      Initiative: 16,
      Accuracy: 14,
      Guard: 14,
      Resist: 12,
      rollBonus: 2,
      DMG: 'd6',
    },
    abilities: 'Underling: Any amount of damage from a hit is enough to kill this creature. It is immune to state damage, environmental damage and damage from missed attacks.',
    description: 'A juvenile goblin pressed into service, crude knife shaking in its hands.',
    tags: ['goblin'],
    deedNames: ["Coward's Cut", "Crude Bow"],
  },
  {
    name: 'Goblin Slicer',
    level: 1,
    role: 'Harrier',
    template: 'Normal',
    TR: 10,
    attributes: {
      HP: 20,
      Speed: 6,
      Initiative: 16,
      Accuracy: 14,
      Guard: 14,
      Resist: 12,
      rollBonus: 2,
      DMG: 'd6',
    },
    abilities: '',
    description: 'Slicers cherish their rusty weapons, giving them names and chiseling crude faces into them.',
    tags: ['goblin'],
    deedNames: ["Cut & Run", "Sharp Rock", "Blood-Spiller"],
  },
  {
    name: 'Goblin Deadeye',
    level: 1,
    role: 'Archer',
    template: 'Normal',
    TR: 10,
    attributes: {
      HP: 20,
      Speed: 5,
      Initiative: 14,
      Accuracy: 16,
      Guard: 12,
      Resist: 12,
      rollBonus: 4,
      DMG: 'd6',
    },
    abilities: '',
    description: 'Goblin archers sleep with their arrowheads dip their arrowheads in filth to inflict lasting disease.',
    tags: ['goblin'],
    deedNames: ["Barbed Arrow", "Poison Arrow"],
  },
  {
    name: 'Goblin Bloodaxe',
    level: 2,
    role: 'Hellion',
    template: 'Normal',
    TR: 20,
    attributes: {
      HP: 50,
      Speed: 6,
      Initiative: 15,
      Accuracy: 17,
      Guard: 13,
      Resist: 15,
      rollBonus: 4,
      DMG: 'd10',
    },
    abilities: "Powerful: This creature's damage dice are one size larger than normal for its level.",
    description: 'A hulking goblin that has embraced pure, unadulterated violence.',
    tags: ['goblin'],
    deedNames: ['Jagged Axe', 'Smashing Strike', 'Bolstering Cleave'],
  },
  {
    name: 'Goblin Warbringer',
    level: 2,
    role: 'Enchanter',
    template: 'Paragon',
    TR: 40,
    attributes: {
      HP: 100,
      Speed: 5,
      Initiative: 13,
      Accuracy: 13,
      Guard: 15,
      Resist: 17,
      rollBonus: 5,
      DMG: 'd6',
    },
    abilities: "Paragon: This creature takes an extra turn at the end of each round. It is immune to effects that would delay its turn.\nCoward: When this creature takes attack damage, if there is an ally within 2 squares, it may spend a reaction ▼ to sweep that ally 1 square. That ally suffers the damage instead.",
    description: 'This goblin chieftain leads from the front, turning their followers into a deadly, coordinated weapon.',
    tags: ['goblin', 'chieftain'],
    deedNames: ["War Blade", "Warbringer's Blessing", "Warbringer's Threat", "Mark for Death"],
  },
  {
    name: 'Goblin Bloodstaff',
    level: 2,
    role: 'Sorcerer',
    template: 'Normal',
    TR: 20,
    attributes: {
      HP: 30,
      Speed: 5,
      Initiative: 13,
      Accuracy: 17,
      Guard: 13,
      Resist: 17,
      rollBonus: 7,
      DMG: 'd8',
    },
    abilities: "",
    description: 'A goblin shaman that wields profane magic, often at a terrible cost to its underlings.',
    tags: ['goblin', 'magic-user'],
    deedNames: ['Staff', 'Shadow Bolt', 'Mud Burst', 'Blood Bomb'],
  },
];
