
import type { DeedData, NewCreature } from '@/lib/types';

export const defaultDeeds: (DeedData & { deedName: string })[] = [
  {
    deedName: "Coward's Cut",
    name: "Coward's Cut",
    tier: 'light',
    target: 'Melee Attack vs Guard',
    range: '1 Creature',
    effects: {
      hit: 'Deal 3 damage (1d6). Move 3.',
      shadow: 'Deal 3 damage (1d6). Move 3.',
    },
    tags: ['melee'],
  },
  {
    deedName: "Crude Bow",
    name: 'Crude Bow',
    tier: 'light',
    target: 'Missile Attack vs Guard',
    range: 'Range 8',
    effects: {
      hit: 'Deal 3 damage (1d6).',
      shadow: 'Deal 3 damage (1d6).',
    },
    tags: ['missile'],
  },
  {
    deedName: "Cut & Run",
    name: 'Cut & Run',
    tier: 'light',
    target: 'Melee Attack vs Guard',
    range: '1 Creature',
    effects: {
      hit: 'Deal 7 damage (2d6). Move 2.',
      shadow: 'Confer bleeding 2.',
    },
    tags: ['melee'],
  },
  {
    deedName: "Sharp Rock",
    name: 'Sharp Rock',
    tier: 'light',
    target: 'Missile Attack vs Guard',
    range: 'Range 8',
    effects: {
      hit: 'Deal 3 damage (1d6).',
      shadow: 'Confer bleeding 2.',
    },
    tags: ['missile'],
  },
  {
    deedName: "Blood-Spiller",
    name: 'Blood-Spiller',
    tier: 'heavy',
    target: 'Melee Attack vs Guard',
    range: '1 Creature',
    effects: {
      base: 'Deal 7 damage (2d6).',
      hit: 'Shove 2. The target suffers double damage from bleeding on this forced movement.',
      shadow: 'The target also becomes toppled.',
    },
    tags: ['melee'],
  },
  {
    deedName: "Barbed Arrow",
    name: 'Barbed Arrow',
    tier: 'light',
    target: 'Missile Attack vs Guard',
    range: 'Range 8',
    effects: {
      hit: 'Deal 7 damage (2d6).',
      shadow: 'Confer bleeding 2.',
    },
    tags: ['missile'],
  },
  {
    deedName: "Poison Arrow",
    name: 'Poison Arrow',
    tier: 'heavy',
    target: 'Missile Attack vs Guard',
    range: 'Range 8',
    effects: {
      base: 'Deal 3 damage (1d6).',
      hit: 'Confer poisoned 2.',
      shadow: 'Confer poisoned 4 instead.',
    },
    tags: ['missile', 'poison'],
  },
];

export const defaultCreatures: (Omit<NewCreature, 'deeds'> & { deedNames: string[] })[] = [
  {
    name: 'Goblin Drudge',
    level: 1,
    role: 'Harrier',
    template: 'Underling',
    TR: 3,
    attributes: {
      HP: 1,
      Speed: 6,
      Initiative: 16,
      Accuracy: 14,
      Guard: 14,
      Resist: 12,
      rollBonus: 2,
      DMG: 'd6',
    },
    abilities: 'Underling: Any amount of damage from a hit is enough to kill this creature. It is immune to state damage, environmental damage and damage from missed attacks.',
    description: 'A juvenile goblin pressed into service, crude knife shaking in its hands.',
    tags: ['goblin'],
    deedNames: ["Coward's Cut", "Crude Bow"],
  },
  {
    name: 'Goblin Slicer',
    level: 1,
    role: 'Harrier',
    template: 'Normal',
    TR: 10,
    attributes: {
      HP: 20,
      Speed: 6,
      Initiative: 16,
      Accuracy: 14,
      Guard: 14,
      Resist: 12,
      rollBonus: 2,
      DMG: 'd6',
    },
    abilities: '',
    description: 'Slicers cherish their rusty weapons, giving them names and chiseling crude faces into them.',
    tags: ['goblin'],
    deedNames: ["Cut & Run", "Sharp Rock", "Blood-Spiller"],
  },
  {
    name: 'Goblin Deadeye',
    level: 1,
    role: 'Archer',
    template: 'Normal',
    TR: 10,
    attributes: {
      HP: 20,
      Speed: 5,
      Initiative: 14,
      Accuracy: 16,
      Guard: 12,
      Resist: 12,
      rollBonus: 4,
      DMG: 'd6',
    },
    abilities: '',
    description: 'Goblin archers sleep with their arrowheads dip their arrowheads in filth to inflict lasting disease.',
    tags: ['goblin'],
    deedNames: ["Barbed Arrow", "Poison Arrow"],
  },
];
